//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Admin.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisa.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisa loom.
        /// </summary>
        public static string AddAnimal {
            get {
                return ResourceManager.GetString("AddAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisa heliklipp.
        /// </summary>
        public static string AddSoundTracks {
            get {
                return ResourceManager.GetString("AddSoundTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loom lisatud.
        /// </summary>
        public static string AnimalAdded {
            get {
                return ResourceManager.GetString("AnimalAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loom kustutatud.
        /// </summary>
        public static string AnimalDeleted {
            get {
                return ResourceManager.GetString("AnimalDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisa pilt.
        /// </summary>
        public static string AnimalDetailsAddImage {
            get {
                return ResourceManager.GetString("AnimalDetailsAddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisa asukoht.
        /// </summary>
        public static string AnimalDetailsAddMapSegment {
            get {
                return ResourceManager.GetString("AnimalDetailsAddMapSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladinakeelne nimetus.
        /// </summary>
        public static string AnimalDetailsBinomialName {
            get {
                return ResourceManager.GetString("AnimalDetailsBinomialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaitsestaatus.
        /// </summary>
        public static string AnimalDetailsConservationStatus {
            get {
                return ResourceManager.GetString("AnimalDetailsConservationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirjeldus.
        /// </summary>
        public static string AnimalDetailsDescription {
            get {
                return ResourceManager.GetString("AnimalDetailsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pildid.
        /// </summary>
        public static string AnimalDetailsImages {
            get {
                return ResourceManager.GetString("AnimalDetailsImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asukoht.
        /// </summary>
        public static string AnimalDetailsMapSegment {
            get {
                return ResourceManager.GetString("AnimalDetailsMapSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nimetus.
        /// </summary>
        public static string AnimalDetailsName {
            get {
                return ResourceManager.GetString("AnimalDetailsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ei ole asukohta.
        /// </summary>
        public static string AnimalDetailsNoMapSegment {
            get {
                return ResourceManager.GetString("AnimalDetailsNoMapSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heliklipid.
        /// </summary>
        public static string AnimalDetailsSoundtracks {
            get {
                return ResourceManager.GetString("AnimalDetailsSoundtracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loomad.
        /// </summary>
        public static string Animals {
            get {
                return ResourceManager.GetString("Animals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagasi loomade nimekirja.
        /// </summary>
        public static string BackToAnimalOverview {
            get {
                return ResourceManager.GetString("BackToAnimalOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagasi piltide nimekirja.
        /// </summary>
        public static string BackToImageOverview {
            get {
                return ResourceManager.GetString("BackToImageOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muuda.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisa koordinaat.
        /// </summary>
        public static string CoordinateAdd {
            get {
                return ResourceManager.GetString("CoordinateAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kustuta koordinaat.
        /// </summary>
        public static string CoordinateDelete {
            get {
                return ResourceManager.GetString("CoordinateDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koordinaadid.
        /// </summary>
        public static string Coordinates {
            get {
                return ResourceManager.GetString("Coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loo.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loodud.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kustuta.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuvasta koordinaadid.
        /// </summary>
        public static string DetectCoorinates {
            get {
                return ResourceManager.GetString("DetectCoorinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisa pilt.
        /// </summary>
        public static string ImageAdd {
            get {
                return ResourceManager.GetString("ImageAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pilt kustutatud.
        /// </summary>
        public static string ImageDeleted {
            get {
                return ResourceManager.GetString("ImageDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nimetus.
        /// </summary>
        public static string ImageDetailsName {
            get {
                return ResourceManager.GetString("ImageDetailsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pildid.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laadi pilt üles.
        /// </summary>
        public static string ImageUpload {
            get {
                return ResourceManager.GetString("ImageUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string ImageUrl {
            get {
                return ResourceManager.GetString("ImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viimati muudetud.
        /// </summary>
        public static string LastChanged {
            get {
                return ResourceManager.GetString("LastChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pikkuskraad.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laiuskraad.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Määra peamiseks.
        /// </summary>
        public static string MakePrimary {
            get {
                return ResourceManager.GetString("MakePrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisa asukoht.
        /// </summary>
        public static string MapSegmentAdd {
            get {
                return ResourceManager.GetString("MapSegmentAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kustuta asukoht.
        /// </summary>
        public static string MapSegmentDelete {
            get {
                return ResourceManager.GetString("MapSegmentDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nimetus.
        /// </summary>
        public static string MapSegmentName {
            get {
                return ResourceManager.GetString("MapSegmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asukohad kaardil.
        /// </summary>
        public static string MapSegments {
            get {
                return ResourceManager.GetString("MapSegments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loomad.
        /// </summary>
        public static string MenuAnimals {
            get {
                return ResourceManager.GetString("MenuAnimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagasiside.
        /// </summary>
        public static string MenuFeedback {
            get {
                return ResourceManager.GetString("MenuFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pildid.
        /// </summary>
        public static string MenuImages {
            get {
                return ResourceManager.GetString("MenuImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asukohad kaardil.
        /// </summary>
        public static string MenuLocationsOnMap {
            get {
                return ResourceManager.GetString("MenuLocationsOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heliklipid.
        /// </summary>
        public static string MenuSoundTracks {
            get {
                return ResourceManager.GetString("MenuSoundTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasutajad.
        /// </summary>
        public static string MenuUsers {
            get {
                return ResourceManager.GetString("MenuUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nimi.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eemalda.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvesta.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otsi.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kustuta asukoht.
        /// </summary>
        public static string SegmentDelete {
            get {
                return ResourceManager.GetString("SegmentDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logi sisse.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisa heliklipp.
        /// </summary>
        public static string SoundtrackAdd {
            get {
                return ResourceManager.GetString("SoundtrackAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nimetus.
        /// </summary>
        public static string SoundtrackName {
            get {
                return ResourceManager.GetString("SoundtrackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soundtracks.
        /// </summary>
        public static string Soundtracks {
            get {
                return ResourceManager.GetString("Soundtracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staatus.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
    }
}
