//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisa.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirjeldus.
        /// </summary>
        public static string AnimalDetailsDescription {
            get {
                return ResourceManager.GetString("AnimalDetailsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heliklipid.
        /// </summary>
        public static string AnimalDetailsSoundTracks {
            get {
                return ResourceManager.GetString("AnimalDetailsSoundTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagasi loomade vaatesse.
        /// </summary>
        public static string BackToAnimals {
            get {
                return ResourceManager.GetString("BackToAnimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loo.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teie veebilehitseja ei toeta seda audio elementi..
        /// </summary>
        public static string ErrorBrowserDoesNotSupportAudio {
            get {
                return ResourceManager.GetString("ErrorBrowserDoesNotSupportAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üle lubatud tähemärkide arvu.
        /// </summary>
        public static string ErrorMaxLength {
            get {
                return ResourceManager.GetString("ErrorMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alla lubatud tähemärkide arvu.
        /// </summary>
        public static string ErrorMinLength {
            get {
                return ResourceManager.GetString("ErrorMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagasiside.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagasisaade saadetud.
        /// </summary>
        public static string FeedbackSent {
            get {
                return ResourceManager.GetString("FeedbackSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aitäh tagasiside eest!.
        /// </summary>
        public static string FeedbackThanks {
            get {
                return ResourceManager.GetString("FeedbackThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anna tagasisidet.
        /// </summary>
        public static string GiveFeedback {
            get {
                return ResourceManager.GetString("GiveFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This web application is brand new. We&apos;d like to improve it. That&apos;s why every feedback is valuable to us. Thank you for taking the time to help us..
        /// </summary>
        public static string GiveFeedbackDescription {
            get {
                return ResourceManager.GetString("GiveFeedbackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaart.
        /// </summary>
        public static string MenuAnimals {
            get {
                return ResourceManager.GetString("MenuAnimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagasiside.
        /// </summary>
        public static string MenuFeedback {
            get {
                return ResourceManager.GetString("MenuFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pildid.
        /// </summary>
        public static string MenuImages {
            get {
                return ResourceManager.GetString("MenuImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asukohad kaardil.
        /// </summary>
        public static string MenuLocationsOnMap {
            get {
                return ResourceManager.GetString("MenuLocationsOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heliklipid.
        /// </summary>
        public static string MenuSoundTracks {
            get {
                return ResourceManager.GetString("MenuSoundTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasutajad.
        /// </summary>
        public static string MenuUsers {
            get {
                return ResourceManager.GetString("MenuUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nimi.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registreeri.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvesta.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otsi.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saada tagasiside.
        /// </summary>
        public static string SendFeedback {
            get {
                return ResourceManager.GetString("SendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logi sisse.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lõpeta jälgimine.
        /// </summary>
        public static string StatsCloseWatch {
            get {
                return ResourceManager.GetString("StatsCloseWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keskmine.
        /// </summary>
        public static string StatsMean {
            get {
                return ResourceManager.GetString("StatsMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punktide arv.
        /// </summary>
        public static string StatsPoints {
            get {
                return ResourceManager.GetString("StatsPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alusta jälgimist.
        /// </summary>
        public static string StatsStartWatch {
            get {
                return ResourceManager.GetString("StatsStartWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aega jäänud.
        /// </summary>
        public static string StatsTimeLeft {
            get {
                return ResourceManager.GetString("StatsTimeLeft", resourceCulture);
            }
        }
    }
}
