// <auto-generated />
using System;
using DAL.App.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.App.EF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190502140708_InitialDbCreation")]
    partial class InitialDbCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Animals.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BinomialName")
                        .HasMaxLength(80);

                    b.Property<Guid?>("ConservationStatusId");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description");

                    b.Property<Guid?>("FeaturedImgId");

                    b.Property<DateTime>("LastEdited");

                    b.Property<Guid?>("MapSegmentId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<Guid?>("ScientificClassificationId");

                    b.HasKey("Id");

                    b.HasIndex("ConservationStatusId");

                    b.HasIndex("FeaturedImgId");

                    b.HasIndex("ScientificClassificationId");

                    b.ToTable("Animal");

                    b.HasData(
                        new
                        {
                            Id = new Guid("90de391c-a3dc-4aa1-9208-011ef4b6718e"),
                            BinomialName = "Halichoerus grypus",
                            ConservationStatusId = new Guid("58b8818d-f4d3-4d39-8906-88b79080fd92"),
                            Created = new DateTime(2019, 5, 2, 17, 7, 7, 616, DateTimeKind.Local).AddTicks(6572),
                            Description = "Hallhüljes (Halichoerus grypus) on loivaliste (Pinnipedia) seltsi hülglaste (Phocidae) sugukonda kuuluv veeimetaja. Hallhüljes on Läänemere imetajatest suurim [1]. Ta on üks kolmest Eestis elavast hülglasest, omanimelise perekonna ainuliik.",
                            FeaturedImgId = new Guid("e0d6dbe3-2fac-45a7-b672-b55e63bb8c45"),
                            LastEdited = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hallhüljes"
                        },
                        new
                        {
                            Id = new Guid("3b233f62-c406-4850-bffa-fbb8809b74a8"),
                            BinomialName = "Panthera leo",
                            ConservationStatusId = new Guid("a2679cb7-2f56-4913-99cc-4e5d97d3bb38"),
                            Created = new DateTime(2019, 5, 2, 17, 7, 7, 618, DateTimeKind.Local).AddTicks(6423),
                            Description = "Lõvid on väga suured ja võimsa kehaehitusega. Isaste kehapikkus on 180–240 cm, saba pikkus 60–90 cm, mass 180–227 kg. Kere on sale, isegi kiitsakas. Pea on erakordselt massiivne, võrdlemisi pika koonuga. Jäsemed on lüheldased ja väga tugevad. Pikk saba lõpeb tutiga. Keha katab lühikene pruunikaskollane karvastik. Täiskasvanud isasloomal on pikk tumedam lakk, mis katab nii kaela, õlgu kui ka rinda.",
                            FeaturedImgId = new Guid("7d0f2cfb-0c8e-4c00-afe0-28b1ed5a9de1"),
                            LastEdited = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lõvi"
                        },
                        new
                        {
                            Id = new Guid("6c10d341-465a-4fc1-902e-d55f58d57a5a"),
                            BinomialName = "Macaca fuscata",
                            ConservationStatusId = new Guid("58b8818d-f4d3-4d39-8906-88b79080fd92"),
                            Created = new DateTime(2019, 5, 2, 17, 7, 7, 618, DateTimeKind.Local).AddTicks(6486),
                            Description = "Jässaka kehaehituse ja tiheda karvakasukaga jaapani makaagid on kõige põhjapoolsema levikuga ahvid. Talvekülmade eest otsivad kaitset kuumaveeallikates. Tegutsevad nii puudel kui maapinnal, ujuvad ja sukelduvad suurepäraselt. Söövad puuvilju, taimede lehti ja juuri, putukaid, limuseid jms, ka pisiimetajaid. Elavad gruppidena, mida juhib tugev isasloom ja kus on selgelt välja kujunenud alluvussuhted. Omavahelisel suhtlemisel on tähtsal kohal häälitsused, miimika ja žestid. Pojad sünnivad enamasti kevad-suvel. Järglaste eest hoolitseb sageli ka isane. Loomaaias on elanud kuni 35 aastat vanaks.",
                            FeaturedImgId = new Guid("9a522da8-aef2-4647-bddd-a88153c1738b"),
                            LastEdited = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jaapani makaak"
                        },
                        new
                        {
                            Id = new Guid("75436cc9-9a97-4d75-9037-e714f286d456"),
                            BinomialName = "Pan troglodytes",
                            ConservationStatusId = new Guid("58b8818d-f4d3-4d39-8906-88b79080fd92"),
                            Created = new DateTime(2019, 5, 2, 17, 7, 7, 618, DateTimeKind.Local).AddTicks(6500),
                            Description = "Asustavad metsi, võsastikke ja kohati ka lagedamaid alasid. Tegutsevad nii puudel kui maapinnal. Aktiivsed päeval, ööbivad puude otsa ehitatud pesades. Söövad puuvilju, lehti, seemneid, marju, putukaid. Vahel söövad šimpansid ka liha, püüdes üheskoos saagiks väiksemaid loomi. Elavad 20–30-isendilistes seltsingutes, kus valitseb keeruline võimujaotus. Karjasisestes suhetes on nad väga sallivad, kuid võõrast karjast sissetungijate vastu vaenulikud. Sigivad läbi aasta, pärast 230-päevast tiinust toob emane ilmale 1 poja. Emast võõrdumine algab u. 5. eluaastast. Suguküpsuse saavutavad 12–15-aastastena. Eluiga kuni 50 a. Geneetiliselt on šimpans inimese lähim elav sugulane. Šimpanseid ohustab vihmametsade hävitamine ja salaküttimine.",
                            FeaturedImgId = new Guid("f249d2ba-5bb4-486d-b0da-c9c0acdac1e3"),
                            LastEdited = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Simpans"
                        },
                        new
                        {
                            Id = new Guid("b493b31f-53ea-4ea3-8774-6c31fd5f5694"),
                            BinomialName = "Phacochoerus africanus",
                            ConservationStatusId = new Guid("58b8818d-f4d3-4d39-8906-88b79080fd92"),
                            Created = new DateTime(2019, 5, 2, 17, 7, 7, 618, DateTimeKind.Local).AddTicks(6513),
                            Description = "Asustavad savanne ja hõredaid põõsastikke, vältides tihedaid metsi. Elavad rühmades, kuhu kuulu-vad 1–3 emist koos põrsastega. Kuldid hoiavad eraldi. Tegutsevad päeval, veetes öö urus, kuhu täiskasvanud sisenevad tagurpidi, sulgedes uruava oma suure tüükalise peaga. Toituvad rohttaimedest, liikudes ringi poolroomates “põlvili”, esijäsemetel on randmeliigese kohal paksud mõhnad. Sigivad aasta läbi, kuigi enim poegi on vihmaperioodil. Jooksuajal teevad isased mootoripodinat meenutavat häält ja katsuvad rammu, surudes teineteist teelt, laubad vastamisi. Emane sünnitab urus 3–4 vöötideta põrsast.",
                            FeaturedImgId = new Guid("86d1c8bd-f68b-4f9f-84bc-19447bf78c71"),
                            LastEdited = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tüügassiga"
                        });
                });

            modelBuilder.Entity("Domain.Animals.AnimalFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AnimalId");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Label")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("AnimalFact");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f15bcc3a-3b5c-4b23-831d-5dc8b326248e"),
                            AnimalId = new Guid("90de391c-a3dc-4aa1-9208-011ef4b6718e"),
                            Description = "Hallhülge eluiga jääb tavaliselt 15–25 aasta vahele. Vanim loodusest leitud isend oli 46-aastane emane.",
                            Label = "Eluiga"
                        },
                        new
                        {
                            Id = new Guid("c32d65a3-d8c8-45f2-82c9-322fe359d177"),
                            AnimalId = new Guid("90de391c-a3dc-4aa1-9208-011ef4b6718e"),
                            Description = "Hallhülge ladinakeelse nimetuse tähendus tuleb kreekakeelsetest sõnadest Halios – meri, khoiros – siga ja grupos – konksnina.",
                            Label = "Nimetus"
                        },
                        new
                        {
                            Id = new Guid("a45b72f3-061c-4e33-b2ce-68ebc8161a6b"),
                            AnimalId = new Guid("3b233f62-c406-4850-bffa-fbb8809b74a8"),
                            Description = "Läbi aegade on lõvi peetud loomade kuningaks. See sai alguse raamatust \"Physiologus\".",
                            Label = "Loomade kuningas"
                        });
                });

            modelBuilder.Entity("Domain.Animals.ConservationStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abbreviation");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ConservationStatus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("46470634-c4af-42b9-8eec-8c117a557f50"),
                            Abbreviation = "EX",
                            Name = "Extinct"
                        },
                        new
                        {
                            Id = new Guid("5e4737fc-82fb-47b5-8337-b6f595ba080e"),
                            Abbreviation = "EW",
                            Name = "Extinct in the wild"
                        },
                        new
                        {
                            Id = new Guid("613315a8-b6f5-49ec-9583-7d33492e7be3"),
                            Abbreviation = "CR",
                            Name = "Critically endangered"
                        },
                        new
                        {
                            Id = new Guid("a5ecde65-5848-404a-a6ef-d42bfe4e97dc"),
                            Abbreviation = "EN",
                            Name = "Endangered"
                        },
                        new
                        {
                            Id = new Guid("a2679cb7-2f56-4913-99cc-4e5d97d3bb38"),
                            Abbreviation = "VU",
                            Name = "Vulnerable"
                        },
                        new
                        {
                            Id = new Guid("09492d41-c971-443d-8717-a360b38ccb81"),
                            Abbreviation = "NT",
                            Name = "Near threatened"
                        },
                        new
                        {
                            Id = new Guid("58b8818d-f4d3-4d39-8906-88b79080fd92"),
                            Abbreviation = "LC",
                            Name = "Least concern"
                        },
                        new
                        {
                            Id = new Guid("74f3d6f7-4f14-42c9-bdeb-1fcb77890a02"),
                            Abbreviation = "DD",
                            Name = "Data deficient"
                        },
                        new
                        {
                            Id = new Guid("ae5e6d70-4365-448c-8edc-4474562e2ff1"),
                            Abbreviation = "NE",
                            Name = "Not evaluated"
                        });
                });

            modelBuilder.Entity("Domain.Animals.MediaInAnimal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AnimalId");

                    b.Property<Guid>("MediaId");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("MediaId");

                    b.ToTable("MediaInAnimal");
                });

            modelBuilder.Entity("Domain.Animals.ScientificClassification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ScientificClassification");
                });

            modelBuilder.Entity("Domain.Animals.SoundTrackInAnimal", b =>
                {
                    b.Property<Guid>("AnimalId");

                    b.Property<Guid>("SoundTrackId");

                    b.Property<Guid>("Id");

                    b.Property<bool>("IsFeatured");

                    b.HasKey("AnimalId", "SoundTrackId");

                    b.HasIndex("SoundTrackId");

                    b.ToTable("SoundTrackInAnimal");

                    b.HasData(
                        new
                        {
                            AnimalId = new Guid("90de391c-a3dc-4aa1-9208-011ef4b6718e"),
                            SoundTrackId = new Guid("e167329f-4473-4267-9c5d-3027f01c57ce"),
                            Id = new Guid("343f8a63-46a4-4916-83f2-859128524f8c"),
                            IsFeatured = true
                        },
                        new
                        {
                            AnimalId = new Guid("3b233f62-c406-4850-bffa-fbb8809b74a8"),
                            SoundTrackId = new Guid("cdbfe51d-e9a1-493c-a611-fbfa1d76cbbb"),
                            Id = new Guid("3604a989-676d-4e78-85f5-42e76d8cd4a5"),
                            IsFeatured = true
                        },
                        new
                        {
                            AnimalId = new Guid("6c10d341-465a-4fc1-902e-d55f58d57a5a"),
                            SoundTrackId = new Guid("ae6e2c2c-1e7d-475b-beec-ffb53130757b"),
                            Id = new Guid("fa8f4bb9-7401-474d-98c4-f5afca6266b1"),
                            IsFeatured = true
                        },
                        new
                        {
                            AnimalId = new Guid("6c10d341-465a-4fc1-902e-d55f58d57a5a"),
                            SoundTrackId = new Guid("022c10d3-1ef8-4606-810a-58dd51fe319b"),
                            Id = new Guid("6d1f32dd-b891-4dab-be2a-83c49ed427cc"),
                            IsFeatured = false
                        },
                        new
                        {
                            AnimalId = new Guid("6c10d341-465a-4fc1-902e-d55f58d57a5a"),
                            SoundTrackId = new Guid("889e743b-3ab8-41a9-b7de-1bda37de9bd0"),
                            Id = new Guid("ffceabee-e2b9-47a0-a812-31f70de552b0"),
                            IsFeatured = false
                        },
                        new
                        {
                            AnimalId = new Guid("6c10d341-465a-4fc1-902e-d55f58d57a5a"),
                            SoundTrackId = new Guid("67b00230-bbd0-40f5-998b-6b4e7b79f31e"),
                            Id = new Guid("09da8cc2-596b-4921-a668-0b260249348f"),
                            IsFeatured = false
                        },
                        new
                        {
                            AnimalId = new Guid("75436cc9-9a97-4d75-9037-e714f286d456"),
                            SoundTrackId = new Guid("4c0154a4-10b5-43c6-ab4a-7b2d4acb638e"),
                            Id = new Guid("b0763070-2ebe-4fb8-80b6-d28e516337ec"),
                            IsFeatured = true
                        },
                        new
                        {
                            AnimalId = new Guid("b493b31f-53ea-4ea3-8774-6c31fd5f5694"),
                            SoundTrackId = new Guid("78829890-edbe-491b-a27d-900f5457606b"),
                            Id = new Guid("6bab48f6-1cc2-415c-9008-ec319212bd6b"),
                            IsFeatured = true
                        });
                });

            modelBuilder.Entity("Domain.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("Description");

                    b.Property<string>("SenderEmail");

                    b.HasKey("Id");

                    b.ToTable("Feedback");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cfc4ec24-6069-4189-9e0c-482849e3fcad"),
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a test feedback",
                            SenderEmail = "bob.test@email.com"
                        });
                });

            modelBuilder.Entity("Domain.Identity.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cc0e99f5-1b03-424d-bddc-442c361f6fa3"),
                            ConcurrencyStamp = "2f22a1f7-05e9-401a-bf98-15270b9204f2",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        });
                });

            modelBuilder.Entity("Domain.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<string>("WorkPosition");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10f58b68-f85b-4526-988e-5eb132aae5b9"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b0335a25-326a-4292-8fb7-376cfdc2fc15",
                            Email = "mikkraudsepp@hotmail.com",
                            EmailConfirmed = false,
                            FirstName = "Mikk",
                            LastName = "Raudsepp",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = new Guid("a226d610-1108-408d-ba66-77c69c760466"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f4c27799-185f-4452-af93-5399be3e2425",
                            Email = "themikkraudsepp@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("Domain.Map.AppMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("AppMap");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1fefc037-df28-4bfe-9f65-65918be312ed"),
                            Name = "Tallinna loomaaia kaart"
                        });
                });

            modelBuilder.Entity("Domain.Map.MapSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AnimalId");

                    b.Property<Guid>("AppMapId");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId")
                        .IsUnique();

                    b.HasIndex("AppMapId");

                    b.ToTable("MapSegment");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ced5e15e-bfa2-40ca-b69f-dd1af627b2c1"),
                            AnimalId = new Guid("90de391c-a3dc-4aa1-9208-011ef4b6718e"),
                            AppMapId = new Guid("1fefc037-df28-4bfe-9f65-65918be312ed"),
                            Latitude = 59.451625300000003,
                            Longitude = 24.717528000000001,
                            Name = "Hallhülge bassein"
                        },
                        new
                        {
                            Id = new Guid("90783308-2044-4dbe-930a-5092798c9932"),
                            AnimalId = new Guid("6c10d341-465a-4fc1-902e-d55f58d57a5a"),
                            AppMapId = new Guid("1fefc037-df28-4bfe-9f65-65918be312ed"),
                            Latitude = 59.451569300000003,
                            Longitude = 24.717741199999999,
                            Name = "Ahvipuur - Jaapani Makaak"
                        },
                        new
                        {
                            Id = new Guid("dd27b43a-d1d6-4e45-a876-2346d4d02a03"),
                            AnimalId = new Guid("3b233f62-c406-4850-bffa-fbb8809b74a8"),
                            AppMapId = new Guid("1fefc037-df28-4bfe-9f65-65918be312ed"),
                            Latitude = 59.4514493,
                            Longitude = 24.717574899999999,
                            Name = "Lõvipuur"
                        },
                        new
                        {
                            Id = new Guid("b6ffd553-bc2e-4f4b-a805-be37b36e0f51"),
                            AnimalId = new Guid("75436cc9-9a97-4d75-9037-e714f286d456"),
                            AppMapId = new Guid("1fefc037-df28-4bfe-9f65-65918be312ed"),
                            Latitude = 59.451469899999999,
                            Longitude = 24.717251099999999,
                            Name = "Simpansite aed"
                        },
                        new
                        {
                            Id = new Guid("1b218311-e37a-4413-9ff8-c31ad5a9b548"),
                            AnimalId = new Guid("b493b31f-53ea-4ea3-8774-6c31fd5f5694"),
                            AppMapId = new Guid("1fefc037-df28-4bfe-9f65-65918be312ed"),
                            Latitude = 59.451567400000002,
                            Longitude = 24.7173722,
                            Name = "Tüügassea aedik"
                        });
                });

            modelBuilder.Entity("Domain.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FileType");

                    b.Property<string>("Name");

                    b.Property<DateTime>("UploadedDateTime");

                    b.Property<Guid>("UploaderUserId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("UploaderUserId");

                    b.ToTable("Media");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0d6dbe3-2fac-45a7-b672-b55e63bb8c45"),
                            FileType = "image",
                            Name = "Seal",
                            UploadedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UploaderUserId = new Guid("10f58b68-f85b-4526-988e-5eb132aae5b9"),
                            Url = "media/image/seal-avatar.jpg"
                        },
                        new
                        {
                            Id = new Guid("7d0f2cfb-0c8e-4c00-afe0-28b1ed5a9de1"),
                            FileType = "image",
                            Name = "Lion",
                            UploadedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UploaderUserId = new Guid("10f58b68-f85b-4526-988e-5eb132aae5b9"),
                            Url = "media/image/lion-avatar.jpg"
                        },
                        new
                        {
                            Id = new Guid("9a522da8-aef2-4647-bddd-a88153c1738b"),
                            FileType = "image",
                            Name = "Japanese macaque",
                            UploadedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UploaderUserId = new Guid("10f58b68-f85b-4526-988e-5eb132aae5b9"),
                            Url = "media/image/japanese-macaque-avatar.jpg"
                        },
                        new
                        {
                            Id = new Guid("86d1c8bd-f68b-4f9f-84bc-19447bf78c71"),
                            FileType = "image",
                            Name = "Warhog",
                            UploadedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UploaderUserId = new Guid("10f58b68-f85b-4526-988e-5eb132aae5b9"),
                            Url = "media/image/warhog-avatar-1.jpg"
                        },
                        new
                        {
                            Id = new Guid("f249d2ba-5bb4-486d-b0da-c9c0acdac1e3"),
                            FileType = "image",
                            Name = "Chimpanzee",
                            UploadedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UploaderUserId = new Guid("10f58b68-f85b-4526-988e-5eb132aae5b9"),
                            Url = "media/image/chimpanzee-avatar-1.jpg"
                        });
                });

            modelBuilder.Entity("Domain.SoundTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FileName");

                    b.Property<string>("FileType");

                    b.Property<string>("Name");

                    b.Property<string>("Reader");

                    b.Property<int>("TimesPlayed");

                    b.Property<string>("TrackLength");

                    b.Property<DateTime>("UploadedDateTime");

                    b.Property<Guid>("UploaderUserId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("UploaderUserId");

                    b.ToTable("SoundTrack");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e167329f-4473-4267-9c5d-3027f01c57ce"),
                            FileType = "mp3",
                            Name = "Seal facts",
                            TimesPlayed = 0,
                            UploadedDateTime = new DateTime(2019, 5, 2, 17, 7, 7, 618, DateTimeKind.Local).AddTicks(7368),
                            UploaderUserId = new Guid("10f58b68-f85b-4526-988e-5eb132aae5b9"),
                            Url = "media/audio/grayseal-1.mp3"
                        },
                        new
                        {
                            Id = new Guid("cdbfe51d-e9a1-493c-a611-fbfa1d76cbbb"),
                            FileType = "mp3",
                            Name = "Lõvi kirjeldus",
                            TimesPlayed = 0,
                            UploadedDateTime = new DateTime(2019, 5, 2, 17, 7, 7, 618, DateTimeKind.Local).AddTicks(7828),
                            UploaderUserId = new Guid("10f58b68-f85b-4526-988e-5eb132aae5b9"),
                            Url = "media/audio/lion-1.mp3"
                        },
                        new
                        {
                            Id = new Guid("ae6e2c2c-1e7d-475b-beec-ffb53130757b"),
                            FileType = "mp3",
                            Name = "Jaapani makaak 1",
                            TimesPlayed = 0,
                            UploadedDateTime = new DateTime(2019, 5, 2, 17, 7, 7, 618, DateTimeKind.Local).AddTicks(7799),
                            UploaderUserId = new Guid("10f58b68-f85b-4526-988e-5eb132aae5b9"),
                            Url = "media/audio/japanese-macaque-1.mp3"
                        },
                        new
                        {
                            Id = new Guid("022c10d3-1ef8-4606-810a-58dd51fe319b"),
                            FileType = "mp3",
                            Name = "Jaapani makaak 2",
                            TimesPlayed = 0,
                            UploadedDateTime = new DateTime(2019, 5, 2, 17, 7, 7, 618, DateTimeKind.Local).AddTicks(7812),
                            UploaderUserId = new Guid("10f58b68-f85b-4526-988e-5eb132aae5b9"),
                            Url = "media/audio/japanese-macaque-2.mp3"
                        },
                        new
                        {
                            Id = new Guid("889e743b-3ab8-41a9-b7de-1bda37de9bd0"),
                            FileType = "mp3",
                            Name = "Jaapani makaak 3",
                            TimesPlayed = 0,
                            UploadedDateTime = new DateTime(2019, 5, 2, 17, 7, 7, 618, DateTimeKind.Local).AddTicks(7820),
                            UploaderUserId = new Guid("10f58b68-f85b-4526-988e-5eb132aae5b9"),
                            Url = "media/audio/japanese-macaque-3.mp3"
                        },
                        new
                        {
                            Id = new Guid("67b00230-bbd0-40f5-998b-6b4e7b79f31e"),
                            FileType = "mp3",
                            Name = "Jaapani makaak 4",
                            TimesPlayed = 0,
                            UploadedDateTime = new DateTime(2019, 5, 2, 17, 7, 7, 618, DateTimeKind.Local).AddTicks(7824),
                            UploaderUserId = new Guid("10f58b68-f85b-4526-988e-5eb132aae5b9"),
                            Url = "media/audio/japanese-macaque-4.mp3"
                        },
                        new
                        {
                            Id = new Guid("4c0154a4-10b5-43c6-ab4a-7b2d4acb638e"),
                            FileType = "mp3",
                            Name = "Kuidas rääkida simpansiga",
                            TimesPlayed = 0,
                            UploadedDateTime = new DateTime(2019, 5, 2, 17, 7, 7, 618, DateTimeKind.Local).AddTicks(7832),
                            UploaderUserId = new Guid("10f58b68-f85b-4526-988e-5eb132aae5b9"),
                            Url = "media/audio/chimpanzee-1.mp3"
                        },
                        new
                        {
                            Id = new Guid("78829890-edbe-491b-a27d-900f5457606b"),
                            FileType = "mp3",
                            Name = "Tüügassiga on imeline loom",
                            TimesPlayed = 0,
                            UploadedDateTime = new DateTime(2019, 5, 2, 17, 7, 7, 618, DateTimeKind.Local).AddTicks(7835),
                            UploaderUserId = new Guid("10f58b68-f85b-4526-988e-5eb132aae5b9"),
                            Url = "media/audio/warhog-1.mp3"
                        });
                });

            modelBuilder.Entity("Domain._Shared.Statuses.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("Domain._Shared.Statuses.StatusInMapSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("ActiveDateTimeFrom");

                    b.Property<DateTime?>("ActiveDateTimeTo");

                    b.Property<bool>("IsActive");

                    b.Property<Guid>("MapSegmentId");

                    b.Property<Guid>("StatusId");

                    b.HasKey("Id");

                    b.HasIndex("MapSegmentId");

                    b.HasIndex("StatusId");

                    b.ToTable("StatusInMapSegment");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<Guid>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("10f58b68-f85b-4526-988e-5eb132aae5b9"),
                            RoleId = new Guid("cc0e99f5-1b03-424d-bddc-442c361f6fa3")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Domain.Animals.Animal", b =>
                {
                    b.HasOne("Domain.Animals.ConservationStatus", "ConservationStatus")
                        .WithMany("Animals")
                        .HasForeignKey("ConservationStatusId");

                    b.HasOne("Domain.Media", "FeaturedImg")
                        .WithMany("Animals")
                        .HasForeignKey("FeaturedImgId");

                    b.HasOne("Domain.Animals.ScientificClassification", "ScientificClassification")
                        .WithMany("Animals")
                        .HasForeignKey("ScientificClassificationId");
                });

            modelBuilder.Entity("Domain.Animals.AnimalFact", b =>
                {
                    b.HasOne("Domain.Animals.Animal", "Animal")
                        .WithMany("AnimalFacts")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.Animals.MediaInAnimal", b =>
                {
                    b.HasOne("Domain.Animals.Animal", "Animal")
                        .WithMany("MediaInAnimals")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Media", "Media")
                        .WithMany("MediaInAnimals")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.Animals.SoundTrackInAnimal", b =>
                {
                    b.HasOne("Domain.Animals.Animal", "Animal")
                        .WithMany("AnimalSoundTracks")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.SoundTrack", "SoundTrack")
                        .WithMany("AnimalSoundtracks")
                        .HasForeignKey("SoundTrackId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.Map.MapSegment", b =>
                {
                    b.HasOne("Domain.Animals.Animal", "Animal")
                        .WithOne("MapSegment")
                        .HasForeignKey("Domain.Map.MapSegment", "AnimalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Map.AppMap", "AppMap")
                        .WithMany("MapSegments")
                        .HasForeignKey("AppMapId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.Media", b =>
                {
                    b.HasOne("Domain.Identity.AppUser", "UploaderUser")
                        .WithMany("Medias")
                        .HasForeignKey("UploaderUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.SoundTrack", b =>
                {
                    b.HasOne("Domain.Identity.AppUser", "UploaderUser")
                        .WithMany("SoundTracks")
                        .HasForeignKey("UploaderUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain._Shared.Statuses.StatusInMapSegment", b =>
                {
                    b.HasOne("Domain.Animals.Animal", "MapSegment")
                        .WithMany()
                        .HasForeignKey("MapSegmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain._Shared.Statuses.Status", "Status")
                        .WithMany("StatusInMapSegments")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Domain.Identity.AppRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Domain.Identity.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Domain.Identity.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Domain.Identity.AppRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Identity.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Domain.Identity.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
