// <auto-generated />
using System;
using DAL.App.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.App.EF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Animals.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BinomialName");

                    b.Property<Guid?>("ConservationStatusId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("DescriptionId");

                    b.Property<Guid?>("FeaturedImgId");

                    b.Property<DateTime>("LastEdited");

                    b.Property<Guid?>("MapSegmentId");

                    b.Property<Guid>("NameId");

                    b.Property<Guid?>("ScientificClassificationId");

                    b.HasKey("Id");

                    b.HasIndex("ConservationStatusId");

                    b.HasIndex("DescriptionId");

                    b.HasIndex("FeaturedImgId");

                    b.HasIndex("NameId");

                    b.HasIndex("ScientificClassificationId");

                    b.ToTable("Animal");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9b70d38-f88c-473f-a915-da3a79e1bd32"),
                            BinomialName = "Halichoerus grypus",
                            ConservationStatusId = new Guid("73c49f8c-356a-4e5d-a880-71666e5b4ab6"),
                            Created = new DateTime(2019, 5, 30, 13, 38, 8, 811, DateTimeKind.Local).AddTicks(1393),
                            DescriptionId = new Guid("1a35aea1-d1f2-404f-9aea-057fdb8f46de"),
                            FeaturedImgId = new Guid("4d189082-332a-42d9-8bf0-8a1369af2595"),
                            LastEdited = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameId = new Guid("b9ec0f4d-d0bb-48fd-a2a1-36e86531b4cc")
                        },
                        new
                        {
                            Id = new Guid("cdd01034-b6e4-464f-acc7-018c6dd6a528"),
                            BinomialName = "Panthera leo",
                            ConservationStatusId = new Guid("780dc291-f2b5-4205-9a7b-7d5fe71b0b5d"),
                            Created = new DateTime(2019, 5, 30, 13, 38, 8, 812, DateTimeKind.Local).AddTicks(1350),
                            DescriptionId = new Guid("a204fab0-4e36-49d0-8431-4f7bb8f8dd60"),
                            FeaturedImgId = new Guid("a4f5879f-dab4-444f-a5a0-8e07f94cb1d2"),
                            LastEdited = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameId = new Guid("953864c7-e5b1-47f5-addd-f1cfa880cd33")
                        },
                        new
                        {
                            Id = new Guid("32770294-faaf-4b95-8e4c-94a7116b7857"),
                            BinomialName = "Macaca fuscata",
                            ConservationStatusId = new Guid("73c49f8c-356a-4e5d-a880-71666e5b4ab6"),
                            Created = new DateTime(2019, 5, 30, 13, 38, 8, 812, DateTimeKind.Local).AddTicks(1537),
                            DescriptionId = new Guid("9bffe23d-e223-40f3-acab-8e46733fc5b0"),
                            FeaturedImgId = new Guid("2578c833-f359-4e63-883c-dcf8f4403740"),
                            LastEdited = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameId = new Guid("a1bd7680-cc7a-4728-8138-177d2f8c075a")
                        },
                        new
                        {
                            Id = new Guid("b05520b0-86f3-45a9-b921-a961a3b43cc2"),
                            BinomialName = "Pan troglodytes",
                            ConservationStatusId = new Guid("73c49f8c-356a-4e5d-a880-71666e5b4ab6"),
                            Created = new DateTime(2019, 5, 30, 13, 38, 8, 812, DateTimeKind.Local).AddTicks(1614),
                            DescriptionId = new Guid("70c61e1e-2081-4175-baa7-0e61293e8ed3"),
                            FeaturedImgId = new Guid("1f0713b8-c4e9-4ebc-a8f6-7fed7cc93aee"),
                            LastEdited = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameId = new Guid("a2233944-65a5-4dbd-a10e-76951285e28f")
                        },
                        new
                        {
                            Id = new Guid("f2fd2868-6a30-42fd-9ed4-b06f158a2ac5"),
                            BinomialName = "Phacochoerus africanus",
                            ConservationStatusId = new Guid("73c49f8c-356a-4e5d-a880-71666e5b4ab6"),
                            Created = new DateTime(2019, 5, 30, 13, 38, 8, 812, DateTimeKind.Local).AddTicks(1679),
                            DescriptionId = new Guid("2752af18-e1fb-4af8-a287-012bc9babc25"),
                            FeaturedImgId = new Guid("a8bdeda0-db5a-46e8-aede-3d1ef4d3a537"),
                            LastEdited = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameId = new Guid("78d439fc-b991-418d-b7c9-9f06a64d32fc")
                        });
                });

            modelBuilder.Entity("Domain.Animals.AnimalFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AnimalId");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("AnimalFact");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0e1d531b-f935-43e6-975c-901032182137"),
                            AnimalId = new Guid("a9b70d38-f88c-473f-a915-da3a79e1bd32"),
                            Description = "Hallhülge eluiga jääb tavaliselt 15–25 aasta vahele. Vanim loodusest leitud isend oli 46-aastane emane.",
                            Label = "Eluiga"
                        },
                        new
                        {
                            Id = new Guid("c6e7058c-2db4-477e-8255-55b70a0421ae"),
                            AnimalId = new Guid("a9b70d38-f88c-473f-a915-da3a79e1bd32"),
                            Description = "Hallhülge ladinakeelse nimetuse tähendus tuleb kreekakeelsetest sõnadest Halios – meri, khoiros – siga ja grupos – konksnina.",
                            Label = "Nimetus"
                        },
                        new
                        {
                            Id = new Guid("43f365f7-c86d-4c09-92d3-bcff1d8219bc"),
                            AnimalId = new Guid("cdd01034-b6e4-464f-acc7-018c6dd6a528"),
                            Description = "Läbi aegade on lõvi peetud loomade kuningaks. See sai alguse raamatust \"Physiologus\".",
                            Label = "Loomade kuningas"
                        });
                });

            modelBuilder.Entity("Domain.Animals.ConservationStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abbreviation");

                    b.Property<Guid>("NameId");

                    b.HasKey("Id");

                    b.HasIndex("NameId");

                    b.ToTable("ConservationStatus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b6a01f6-95db-4004-b947-c4f9b4e7a8f4"),
                            Abbreviation = "EX",
                            NameId = new Guid("b90153c2-30c6-46fc-b349-98a061d70737")
                        },
                        new
                        {
                            Id = new Guid("f4d3b9d5-6a59-4585-a376-73c92e72d41c"),
                            Abbreviation = "EW",
                            NameId = new Guid("802f783e-0f6b-46cd-bd3a-624dd71fd365")
                        },
                        new
                        {
                            Id = new Guid("50d53b38-19fe-49a7-b3b8-7fda571d2dde"),
                            Abbreviation = "CR",
                            NameId = new Guid("7de9ce19-9446-48a8-aae7-94b9580adf6f")
                        },
                        new
                        {
                            Id = new Guid("dab80580-7c4d-4b9d-b587-55a179f9c0d1"),
                            Abbreviation = "EN",
                            NameId = new Guid("843cadc1-b5ec-4f6f-9eef-ee326a22e8a9")
                        },
                        new
                        {
                            Id = new Guid("780dc291-f2b5-4205-9a7b-7d5fe71b0b5d"),
                            Abbreviation = "VU",
                            NameId = new Guid("be367196-fe95-49fd-86b6-d2aafb6f1f6d")
                        },
                        new
                        {
                            Id = new Guid("dabe1fca-51bf-445d-98c1-ba76b81a65ce"),
                            Abbreviation = "NT",
                            NameId = new Guid("b61de002-eb12-4a9b-81c9-c82b5e09427d")
                        },
                        new
                        {
                            Id = new Guid("73c49f8c-356a-4e5d-a880-71666e5b4ab6"),
                            Abbreviation = "LC",
                            NameId = new Guid("17dd693e-a778-446c-a144-58268cd15106")
                        },
                        new
                        {
                            Id = new Guid("4d0bf831-8fc8-4068-913f-0dd1d20c76e6"),
                            Abbreviation = "DD",
                            NameId = new Guid("5b65fdaf-5e96-4224-9230-fd1c6bdc3f6c")
                        },
                        new
                        {
                            Id = new Guid("b5aee811-c222-4ecd-9a07-fe185071e0db"),
                            Abbreviation = "NE",
                            NameId = new Guid("90a99419-2008-455f-8cbb-be8ea66a1ec5")
                        });
                });

            modelBuilder.Entity("Domain.Animals.MediaInAnimal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AnimalId");

                    b.Property<Guid>("MediaId");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("MediaId");

                    b.ToTable("MediaInAnimal");
                });

            modelBuilder.Entity("Domain.Animals.ScientificClassification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.HasKey("Id");

                    b.ToTable("ScientificClassification");
                });

            modelBuilder.Entity("Domain.Animals.SoundTrackInAnimal", b =>
                {
                    b.Property<Guid>("AnimalId");

                    b.Property<Guid>("SoundTrackId");

                    b.Property<Guid>("Id");

                    b.Property<bool>("IsFeatured");

                    b.HasKey("AnimalId", "SoundTrackId");

                    b.HasIndex("SoundTrackId");

                    b.ToTable("SoundTrackInAnimal");

                    b.HasData(
                        new
                        {
                            AnimalId = new Guid("a9b70d38-f88c-473f-a915-da3a79e1bd32"),
                            SoundTrackId = new Guid("c754da9b-74f5-4528-b571-0bb096b7ef0f"),
                            Id = new Guid("09ed8c77-5f39-4f6e-8b50-6e676063db03"),
                            IsFeatured = true
                        },
                        new
                        {
                            AnimalId = new Guid("cdd01034-b6e4-464f-acc7-018c6dd6a528"),
                            SoundTrackId = new Guid("e4ae86e6-5880-465b-aa66-cadadd817cac"),
                            Id = new Guid("da6eef37-6652-4ddd-a2d5-657076dedab9"),
                            IsFeatured = true
                        },
                        new
                        {
                            AnimalId = new Guid("32770294-faaf-4b95-8e4c-94a7116b7857"),
                            SoundTrackId = new Guid("9339e128-5847-4cca-9ad7-5748ab7e8fc2"),
                            Id = new Guid("4bca50ae-25f3-4a7b-9ed6-8ae3d1e36114"),
                            IsFeatured = true
                        },
                        new
                        {
                            AnimalId = new Guid("32770294-faaf-4b95-8e4c-94a7116b7857"),
                            SoundTrackId = new Guid("48f37e93-4023-4b41-bc21-af97382ed82b"),
                            Id = new Guid("afb40cad-05a8-4480-a011-38e9f923fde1"),
                            IsFeatured = false
                        },
                        new
                        {
                            AnimalId = new Guid("32770294-faaf-4b95-8e4c-94a7116b7857"),
                            SoundTrackId = new Guid("bad860ee-36c0-40c8-b85c-500a8d129d25"),
                            Id = new Guid("3b47aec1-d566-47c8-8873-76ee3beaaf39"),
                            IsFeatured = false
                        },
                        new
                        {
                            AnimalId = new Guid("32770294-faaf-4b95-8e4c-94a7116b7857"),
                            SoundTrackId = new Guid("bcfeb077-6337-422e-ba6b-9d8cfc0a1150"),
                            Id = new Guid("2e596d22-a575-4396-aa4c-a7c65c2ea99f"),
                            IsFeatured = false
                        },
                        new
                        {
                            AnimalId = new Guid("b05520b0-86f3-45a9-b921-a961a3b43cc2"),
                            SoundTrackId = new Guid("448e5bdf-e43f-43ef-a5a3-bd59d3ebf7f9"),
                            Id = new Guid("256acd8c-1018-49fd-9f59-f72721f0f6e7"),
                            IsFeatured = true
                        },
                        new
                        {
                            AnimalId = new Guid("f2fd2868-6a30-42fd-9ed4-b06f158a2ac5"),
                            SoundTrackId = new Guid("92228787-d505-4ec9-8deb-b04fdc3f0acf"),
                            Id = new Guid("eca17f60-eefd-4bad-b847-e584fd158bec"),
                            IsFeatured = true
                        });
                });

            modelBuilder.Entity("Domain.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("SenderEmail");

                    b.HasKey("Id");

                    b.ToTable("Feedback");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ee277506-21b3-41f4-bb30-f12272cc56e5"),
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a test feedback",
                            SenderEmail = "bob.test@email.com"
                        });
                });

            modelBuilder.Entity("Domain.Identity.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2b913302-415f-4ec2-9c24-82a7bac22eef"),
                            ConcurrencyStamp = "6cbcc069-e4fa-422a-bbdb-fcf9a6663438",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        });
                });

            modelBuilder.Entity("Domain.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<string>("WorkPosition");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fdc54f6e-c086-4649-b957-90c1d75b1416"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1fcb5843-2914-490d-a317-d8aa8c760336",
                            Email = "mikkraudsepp@hotmail.com",
                            EmailConfirmed = false,
                            FirstName = "Mikk",
                            LastName = "Raudsepp",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAELI5ojPLGNuB7ry/fu4lOA8nWBb4qT99TB1AVkfmL5AVAbjLDkmV8AtZLZ8XEyEusA==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = new Guid("0894321a-bb5d-436c-beb9-ddecafabac23"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ee09d5c0-5af4-4b95-a5d5-3ad07db3b50e",
                            Email = "themikkraudsepp@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEC1WrS6YWn6rSBBvT1BxRFbSoXvtirCPBP7go2hZIrzppOy2TA4+BhE+u4Yk1bHHOg==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("Domain.Map.AppMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.HasKey("Id");

                    b.ToTable("AppMap");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d18419f5-19ca-4d3b-a74d-daf44da89934"),
                            Name = "Tallinna loomaaia kaart"
                        });
                });

            modelBuilder.Entity("Domain.Map.GeoCoordinate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<Guid>("MapSegmentId");

                    b.HasKey("Id");

                    b.HasIndex("MapSegmentId");

                    b.ToTable("GeoCoordinate");

                    b.HasData(
                        new
                        {
                            Id = new Guid("912fa574-ab18-45e3-8077-07851cd4e10c"),
                            Created = new DateTime(2019, 5, 30, 13, 38, 8, 813, DateTimeKind.Local).AddTicks(8241),
                            Latitude = 59.451625300000003,
                            Longitude = 24.717528000000001,
                            MapSegmentId = new Guid("2e2eab20-6483-4661-9a01-93443e9432a7")
                        },
                        new
                        {
                            Id = new Guid("c0246b32-f0b5-435b-af7b-53d40d1f7d56"),
                            Created = new DateTime(2019, 5, 30, 13, 38, 8, 813, DateTimeKind.Local).AddTicks(9926),
                            Latitude = 59.451569300000003,
                            Longitude = 24.717741199999999,
                            MapSegmentId = new Guid("8e6c2633-e92f-457b-a0b8-fceaaabbaf0d")
                        },
                        new
                        {
                            Id = new Guid("a15fad4d-fe58-42a8-b2bc-337da12a5764"),
                            Created = new DateTime(2019, 5, 30, 13, 38, 8, 813, DateTimeKind.Local).AddTicks(9982),
                            Latitude = 59.4514493,
                            Longitude = 24.717574899999999,
                            MapSegmentId = new Guid("44c969b4-9797-416e-8fa4-fd22a162aa0c")
                        },
                        new
                        {
                            Id = new Guid("2a6e1be2-ba6b-4076-adc0-d9352e294e57"),
                            Created = new DateTime(2019, 5, 30, 13, 38, 8, 814, DateTimeKind.Local).AddTicks(20),
                            Latitude = 59.451469899999999,
                            Longitude = 24.717251099999999,
                            MapSegmentId = new Guid("1fd771ee-b64b-451a-9d50-7b3cfc451ec3")
                        },
                        new
                        {
                            Id = new Guid("d8df83d6-6f1c-4812-b6db-64b9e8ac8905"),
                            Created = new DateTime(2019, 5, 30, 13, 38, 8, 814, DateTimeKind.Local).AddTicks(56),
                            Latitude = 59.451567400000002,
                            Longitude = 24.7173722,
                            MapSegmentId = new Guid("04f5b970-5df7-41ca-9db1-3880d64b539f")
                        });
                });

            modelBuilder.Entity("Domain.Map.MapSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AnimalId");

                    b.Property<Guid?>("AppMapId");

                    b.Property<Guid>("NameId");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId")
                        .IsUnique()
                        .HasFilter("[AnimalId] IS NOT NULL");

                    b.HasIndex("AppMapId");

                    b.HasIndex("NameId");

                    b.ToTable("MapSegment");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2e2eab20-6483-4661-9a01-93443e9432a7"),
                            AnimalId = new Guid("a9b70d38-f88c-473f-a915-da3a79e1bd32"),
                            AppMapId = new Guid("d18419f5-19ca-4d3b-a74d-daf44da89934"),
                            NameId = new Guid("365173d7-2339-4722-8236-40845c621858")
                        },
                        new
                        {
                            Id = new Guid("8e6c2633-e92f-457b-a0b8-fceaaabbaf0d"),
                            AnimalId = new Guid("32770294-faaf-4b95-8e4c-94a7116b7857"),
                            AppMapId = new Guid("d18419f5-19ca-4d3b-a74d-daf44da89934"),
                            NameId = new Guid("17566ca3-1bfa-4388-a195-a8d2d8081682")
                        },
                        new
                        {
                            Id = new Guid("44c969b4-9797-416e-8fa4-fd22a162aa0c"),
                            AnimalId = new Guid("cdd01034-b6e4-464f-acc7-018c6dd6a528"),
                            AppMapId = new Guid("d18419f5-19ca-4d3b-a74d-daf44da89934"),
                            NameId = new Guid("1282b083-32af-4cc8-9577-96020c7049d1")
                        },
                        new
                        {
                            Id = new Guid("1fd771ee-b64b-451a-9d50-7b3cfc451ec3"),
                            AnimalId = new Guid("b05520b0-86f3-45a9-b921-a961a3b43cc2"),
                            AppMapId = new Guid("d18419f5-19ca-4d3b-a74d-daf44da89934"),
                            NameId = new Guid("0b9ae366-0e78-47cc-a30d-aa2c7d4d57eb")
                        },
                        new
                        {
                            Id = new Guid("04f5b970-5df7-41ca-9db1-3880d64b539f"),
                            AnimalId = new Guid("f2fd2868-6a30-42fd-9ed4-b06f158a2ac5"),
                            AppMapId = new Guid("d18419f5-19ca-4d3b-a74d-daf44da89934"),
                            NameId = new Guid("0056883d-1d16-4488-9b08-da57588c684c")
                        });
                });

            modelBuilder.Entity("Domain.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FileType");

                    b.Property<string>("Name");

                    b.Property<DateTime>("UploadedDateTime");

                    b.Property<Guid?>("UploaderUserId");

                    b.Property<string>("Url")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UploaderUserId");

                    b.ToTable("Media");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4d189082-332a-42d9-8bf0-8a1369af2595"),
                            FileType = "image",
                            Name = "Seal",
                            UploadedDateTime = new DateTime(2019, 5, 30, 13, 38, 8, 808, DateTimeKind.Local).AddTicks(6471),
                            UploaderUserId = new Guid("fdc54f6e-c086-4649-b957-90c1d75b1416"),
                            Url = "media/image/seal-avatar.jpg"
                        },
                        new
                        {
                            Id = new Guid("a4f5879f-dab4-444f-a5a0-8e07f94cb1d2"),
                            FileType = "image",
                            Name = "Lion",
                            UploadedDateTime = new DateTime(2019, 5, 30, 13, 38, 8, 810, DateTimeKind.Local).AddTicks(9621),
                            UploaderUserId = new Guid("fdc54f6e-c086-4649-b957-90c1d75b1416"),
                            Url = "media/image/lion-avatar.jpg"
                        },
                        new
                        {
                            Id = new Guid("2578c833-f359-4e63-883c-dcf8f4403740"),
                            FileType = "image",
                            Name = "Japanese macaque",
                            UploadedDateTime = new DateTime(2019, 5, 30, 13, 38, 8, 810, DateTimeKind.Local).AddTicks(9653),
                            UploaderUserId = new Guid("fdc54f6e-c086-4649-b957-90c1d75b1416"),
                            Url = "media/image/japanese-macaque-avatar.jpg"
                        },
                        new
                        {
                            Id = new Guid("a8bdeda0-db5a-46e8-aede-3d1ef4d3a537"),
                            FileType = "image",
                            Name = "Warhog",
                            UploadedDateTime = new DateTime(2019, 5, 30, 13, 38, 8, 810, DateTimeKind.Local).AddTicks(9659),
                            UploaderUserId = new Guid("fdc54f6e-c086-4649-b957-90c1d75b1416"),
                            Url = "media/image/warhog-avatar-1.jpg"
                        },
                        new
                        {
                            Id = new Guid("1f0713b8-c4e9-4ebc-a8f6-7fed7cc93aee"),
                            FileType = "image",
                            Name = "Chimpanzee",
                            UploadedDateTime = new DateTime(2019, 5, 30, 13, 38, 8, 810, DateTimeKind.Local).AddTicks(9666),
                            UploaderUserId = new Guid("fdc54f6e-c086-4649-b957-90c1d75b1416"),
                            Url = "media/image/chimpanzee-avatar-1.jpg"
                        });
                });

            modelBuilder.Entity("Domain.MultiLangString", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Value")
                        .HasMaxLength(10240);

                    b.HasKey("Id");

                    b.ToTable("MultiLangString");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b90153c2-30c6-46fc-b349-98a061d70737"),
                            Value = "Välja surnud"
                        },
                        new
                        {
                            Id = new Guid("802f783e-0f6b-46cd-bd3a-624dd71fd365"),
                            Value = "Looduses välja surnud"
                        },
                        new
                        {
                            Id = new Guid("7de9ce19-9446-48a8-aae7-94b9580adf6f"),
                            Value = "Äärmiselt ohustatud"
                        },
                        new
                        {
                            Id = new Guid("843cadc1-b5ec-4f6f-9eef-ee326a22e8a9"),
                            Value = "Eriti ohustatud"
                        },
                        new
                        {
                            Id = new Guid("be367196-fe95-49fd-86b6-d2aafb6f1f6d"),
                            Value = "Ohualdis"
                        },
                        new
                        {
                            Id = new Guid("b61de002-eb12-4a9b-81c9-c82b5e09427d"),
                            Value = "Ohulähedane"
                        },
                        new
                        {
                            Id = new Guid("dabe1fca-51bf-445d-98c1-ba76b81a65ce")
                        },
                        new
                        {
                            Id = new Guid("17dd693e-a778-446c-a144-58268cd15106"),
                            Value = "Ohuväline"
                        },
                        new
                        {
                            Id = new Guid("5b65fdaf-5e96-4224-9230-fd1c6bdc3f6c"),
                            Value = "Andmed puudulikud"
                        },
                        new
                        {
                            Id = new Guid("90a99419-2008-455f-8cbb-be8ea66a1ec5"),
                            Value = "Määramata"
                        },
                        new
                        {
                            Id = new Guid("b9ec0f4d-d0bb-48fd-a2a1-36e86531b4cc"),
                            Value = "Hallhüljes"
                        },
                        new
                        {
                            Id = new Guid("1a35aea1-d1f2-404f-9aea-057fdb8f46de"),
                            Value = "Hallhüljes (Halichoerus grypus) on loivaliste (Pinnipedia) seltsi hülglaste (Phocidae) sugukonda kuuluv veeimetaja. Hallhüljes on Läänemere imetajatest suurim [1]. Ta on üks kolmest Eestis elavast hülglasest, omanimelise perekonna ainuliik."
                        },
                        new
                        {
                            Id = new Guid("953864c7-e5b1-47f5-addd-f1cfa880cd33"),
                            Value = "Lõvi"
                        },
                        new
                        {
                            Id = new Guid("a204fab0-4e36-49d0-8431-4f7bb8f8dd60"),
                            Value = "Lõvid on väga suured ja võimsa kehaehitusega. Isaste kehapikkus on 180–240 cm, saba pikkus 60–90 cm, mass 180–227 kg. Kere on sale, isegi kiitsakas. Pea on erakordselt massiivne, võrdlemisi pika koonuga. Jäsemed on lüheldased ja väga tugevad. Pikk saba lõpeb tutiga. Keha katab lühikene pruunikaskollane karvastik. Täiskasvanud isasloomal on pikk tumedam lakk, mis katab nii kaela, õlgu kui ka rinda."
                        },
                        new
                        {
                            Id = new Guid("a1bd7680-cc7a-4728-8138-177d2f8c075a"),
                            Value = "Jaapani makaak"
                        },
                        new
                        {
                            Id = new Guid("9bffe23d-e223-40f3-acab-8e46733fc5b0"),
                            Value = "Jässaka kehaehituse ja tiheda karvakasukaga jaapani makaagid on kõige põhjapoolsema levikuga ahvid. Talvekülmade eest otsivad kaitset kuumaveeallikates. Tegutsevad nii puudel kui maapinnal, ujuvad ja sukelduvad suurepäraselt. Söövad puuvilju, taimede lehti ja juuri, putukaid, limuseid jms, ka pisiimetajaid. Elavad gruppidena, mida juhib tugev isasloom ja kus on selgelt välja kujunenud alluvussuhted. Omavahelisel suhtlemisel on tähtsal kohal häälitsused, miimika ja žestid. Pojad sünnivad enamasti kevad-suvel. Järglaste eest hoolitseb sageli ka isane. Loomaaias on elanud kuni 35 aastat vanaks."
                        },
                        new
                        {
                            Id = new Guid("a2233944-65a5-4dbd-a10e-76951285e28f"),
                            Value = "Šimpans"
                        },
                        new
                        {
                            Id = new Guid("70c61e1e-2081-4175-baa7-0e61293e8ed3"),
                            Value = "Asustavad metsi, võsastikke ja kohati ka lagedamaid alasid. Tegutsevad nii puudel kui maapinnal. Aktiivsed päeval, ööbivad puude otsa ehitatud pesades. Söövad puuvilju, lehti, seemneid, marju, putukaid. Vahel söövad šimpansid ka liha, püüdes üheskoos saagiks väiksemaid loomi. Elavad 20–30-isendilistes seltsingutes, kus valitseb keeruline võimujaotus. Karjasisestes suhetes on nad väga sallivad, kuid võõrast karjast sissetungijate vastu vaenulikud. Sigivad läbi aasta, pärast 230-päevast tiinust toob emane ilmale 1 poja. Emast võõrdumine algab u. 5. eluaastast. Suguküpsuse saavutavad 12–15-aastastena. Eluiga kuni 50 a. Geneetiliselt on šimpans inimese lähim elav sugulane. Šimpanseid ohustab vihmametsade hävitamine ja salaküttimine."
                        },
                        new
                        {
                            Id = new Guid("78d439fc-b991-418d-b7c9-9f06a64d32fc"),
                            Value = "Tüügassiga"
                        },
                        new
                        {
                            Id = new Guid("2752af18-e1fb-4af8-a287-012bc9babc25"),
                            Value = "Asustavad savanne ja hõredaid põõsastikke, vältides tihedaid metsi. Elavad rühmades, kuhu kuulu-vad 1–3 emist koos põrsastega. Kuldid hoiavad eraldi. Tegutsevad päeval, veetes öö urus, kuhu täiskasvanud sisenevad tagurpidi, sulgedes uruava oma suure tüükalise peaga. Toituvad rohttaimedest, liikudes ringi poolroomates “põlvili”, esijäsemetel on randmeliigese kohal paksud mõhnad. Sigivad aasta läbi, kuigi enim poegi on vihmaperioodil. Jooksuajal teevad isased mootoripodinat meenutavat häält ja katsuvad rammu, surudes teineteist teelt, laubad vastamisi. Emane sünnitab urus 3–4 vöötideta põrsast."
                        },
                        new
                        {
                            Id = new Guid("365173d7-2339-4722-8236-40845c621858"),
                            Value = "Hallhülge bassein"
                        },
                        new
                        {
                            Id = new Guid("17566ca3-1bfa-4388-a195-a8d2d8081682"),
                            Value = "Ahvipuur - Jaapani Makaak"
                        },
                        new
                        {
                            Id = new Guid("1282b083-32af-4cc8-9577-96020c7049d1"),
                            Value = "Lõvipuur"
                        },
                        new
                        {
                            Id = new Guid("0b9ae366-0e78-47cc-a30d-aa2c7d4d57eb"),
                            Value = "Šimpansite aed"
                        },
                        new
                        {
                            Id = new Guid("0056883d-1d16-4488-9b08-da57588c684c"),
                            Value = "Tüügassea aedik"
                        });
                });

            modelBuilder.Entity("Domain.SoundTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FileName");

                    b.Property<string>("FileType");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("Reader");

                    b.Property<int>("TimesPlayed");

                    b.Property<string>("TrackLength");

                    b.Property<DateTime>("UploadedDateTime");

                    b.Property<Guid>("UploaderUserId");

                    b.Property<string>("Url")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UploaderUserId");

                    b.ToTable("SoundTrack");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c754da9b-74f5-4528-b571-0bb096b7ef0f"),
                            FileType = "mp3",
                            Name = "Seal facts",
                            TimesPlayed = 0,
                            UploadedDateTime = new DateTime(2019, 5, 30, 13, 38, 8, 812, DateTimeKind.Local).AddTicks(4972),
                            UploaderUserId = new Guid("fdc54f6e-c086-4649-b957-90c1d75b1416"),
                            Url = "media/audio/grayseal-1.mp3"
                        },
                        new
                        {
                            Id = new Guid("e4ae86e6-5880-465b-aa66-cadadd817cac"),
                            FileType = "mp3",
                            Name = "Lõvi kirjeldus",
                            TimesPlayed = 0,
                            UploadedDateTime = new DateTime(2019, 5, 30, 13, 38, 8, 812, DateTimeKind.Local).AddTicks(7086),
                            UploaderUserId = new Guid("fdc54f6e-c086-4649-b957-90c1d75b1416"),
                            Url = "media/audio/lion-1.mp3"
                        },
                        new
                        {
                            Id = new Guid("9339e128-5847-4cca-9ad7-5748ab7e8fc2"),
                            FileType = "mp3",
                            Name = "Jaapani makaak 1",
                            TimesPlayed = 0,
                            UploadedDateTime = new DateTime(2019, 5, 30, 13, 38, 8, 812, DateTimeKind.Local).AddTicks(7043),
                            UploaderUserId = new Guid("fdc54f6e-c086-4649-b957-90c1d75b1416"),
                            Url = "media/audio/japanese-macaque-1.mp3"
                        },
                        new
                        {
                            Id = new Guid("48f37e93-4023-4b41-bc21-af97382ed82b"),
                            FileType = "mp3",
                            Name = "Jaapani makaak 2",
                            TimesPlayed = 0,
                            UploadedDateTime = new DateTime(2019, 5, 30, 13, 38, 8, 812, DateTimeKind.Local).AddTicks(7064),
                            UploaderUserId = new Guid("fdc54f6e-c086-4649-b957-90c1d75b1416"),
                            Url = "media/audio/japanese-macaque-2.mp3"
                        },
                        new
                        {
                            Id = new Guid("bad860ee-36c0-40c8-b85c-500a8d129d25"),
                            FileType = "mp3",
                            Name = "Jaapani makaak 3",
                            TimesPlayed = 0,
                            UploadedDateTime = new DateTime(2019, 5, 30, 13, 38, 8, 812, DateTimeKind.Local).AddTicks(7075),
                            UploaderUserId = new Guid("fdc54f6e-c086-4649-b957-90c1d75b1416"),
                            Url = "media/audio/japanese-macaque-3.mp3"
                        },
                        new
                        {
                            Id = new Guid("bcfeb077-6337-422e-ba6b-9d8cfc0a1150"),
                            FileType = "mp3",
                            Name = "Jaapani makaak 4",
                            TimesPlayed = 0,
                            UploadedDateTime = new DateTime(2019, 5, 30, 13, 38, 8, 812, DateTimeKind.Local).AddTicks(7081),
                            UploaderUserId = new Guid("fdc54f6e-c086-4649-b957-90c1d75b1416"),
                            Url = "media/audio/japanese-macaque-4.mp3"
                        },
                        new
                        {
                            Id = new Guid("448e5bdf-e43f-43ef-a5a3-bd59d3ebf7f9"),
                            FileType = "mp3",
                            Name = "Kuidas rääkida šimpansiga",
                            TimesPlayed = 0,
                            UploadedDateTime = new DateTime(2019, 5, 30, 13, 38, 8, 812, DateTimeKind.Local).AddTicks(7093),
                            UploaderUserId = new Guid("fdc54f6e-c086-4649-b957-90c1d75b1416"),
                            Url = "media/audio/chimpanzee-1.mp3"
                        },
                        new
                        {
                            Id = new Guid("92228787-d505-4ec9-8deb-b04fdc3f0acf"),
                            FileType = "mp3",
                            Name = "Tüügassiga on imeline loom",
                            TimesPlayed = 0,
                            UploadedDateTime = new DateTime(2019, 5, 30, 13, 38, 8, 812, DateTimeKind.Local).AddTicks(7100),
                            UploaderUserId = new Guid("fdc54f6e-c086-4649-b957-90c1d75b1416"),
                            Url = "media/audio/warhog-1.mp3"
                        });
                });

            modelBuilder.Entity("Domain.Translation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Culture")
                        .HasMaxLength(5);

                    b.Property<Guid>("MultiLangStringId");

                    b.Property<string>("Value")
                        .HasMaxLength(10240);

                    b.HasKey("Id");

                    b.HasIndex("MultiLangStringId");

                    b.ToTable("Translation");

                    b.HasData(
                        new
                        {
                            Id = new Guid("578cebbc-bac4-4b38-aa0d-32ac0739bcb8"),
                            Culture = "en",
                            MultiLangStringId = new Guid("b90153c2-30c6-46fc-b349-98a061d70737"),
                            Value = "Extinct"
                        },
                        new
                        {
                            Id = new Guid("2a1e0740-1287-4315-bc69-2b34cfe1f297"),
                            Culture = "en",
                            MultiLangStringId = new Guid("802f783e-0f6b-46cd-bd3a-624dd71fd365"),
                            Value = "Extinct in the wild"
                        },
                        new
                        {
                            Id = new Guid("d0e2840d-7b96-4888-a688-9cd54f935e4e"),
                            Culture = "en",
                            MultiLangStringId = new Guid("7de9ce19-9446-48a8-aae7-94b9580adf6f"),
                            Value = "Critically endangered"
                        },
                        new
                        {
                            Id = new Guid("b96d4118-d796-4da5-b171-2894e03080a2"),
                            Culture = "en",
                            MultiLangStringId = new Guid("843cadc1-b5ec-4f6f-9eef-ee326a22e8a9"),
                            Value = "Endangered"
                        },
                        new
                        {
                            Id = new Guid("d5b3357a-8b9f-4c35-af5e-ec1763842819"),
                            Culture = "en",
                            MultiLangStringId = new Guid("be367196-fe95-49fd-86b6-d2aafb6f1f6d"),
                            Value = "Vulnerable"
                        },
                        new
                        {
                            Id = new Guid("90276a8e-eca7-4563-9e46-231d518b8d7a"),
                            Culture = "en",
                            MultiLangStringId = new Guid("b61de002-eb12-4a9b-81c9-c82b5e09427d"),
                            Value = "Near threatened"
                        },
                        new
                        {
                            Id = new Guid("bb07f445-a8bc-494e-b9e3-22e14b287839"),
                            Culture = "en",
                            MultiLangStringId = new Guid("17dd693e-a778-446c-a144-58268cd15106"),
                            Value = "Least concern"
                        },
                        new
                        {
                            Id = new Guid("00a2e27b-3340-415e-9d15-e69436fd8d24"),
                            Culture = "en",
                            MultiLangStringId = new Guid("5b65fdaf-5e96-4224-9230-fd1c6bdc3f6c"),
                            Value = "Data deficient"
                        },
                        new
                        {
                            Id = new Guid("f556338c-5733-452f-aeed-9af2df8419da"),
                            Culture = "en",
                            MultiLangStringId = new Guid("90a99419-2008-455f-8cbb-be8ea66a1ec5"),
                            Value = "Not evaluated"
                        },
                        new
                        {
                            Id = new Guid("9c0b637a-bc56-465f-ad75-3441c1c2044b"),
                            Culture = "en",
                            MultiLangStringId = new Guid("b9ec0f4d-d0bb-48fd-a2a1-36e86531b4cc"),
                            Value = "Gray seal"
                        },
                        new
                        {
                            Id = new Guid("2dc30082-5f4d-44de-9ab1-6f36d7c3172c"),
                            Culture = "en",
                            MultiLangStringId = new Guid("1a35aea1-d1f2-404f-9aea-057fdb8f46de"),
                            Value = "Hallhüljes (Halichoerus grypus) on loivaliste (Pinnipedia) seltsi hülglaste (Phocidae) sugukonda kuuluv veeimetaja. Hallhüljes on Läänemere imetajatest suurim [1]. Ta on üks kolmest Eestis elavast hülglasest, omanimelise perekonna ainuliik."
                        },
                        new
                        {
                            Id = new Guid("91a0c1ff-24e7-40d5-9d5d-0ec7fdee9e0d"),
                            Culture = "en",
                            MultiLangStringId = new Guid("953864c7-e5b1-47f5-addd-f1cfa880cd33"),
                            Value = "Lion"
                        },
                        new
                        {
                            Id = new Guid("3dcc4efd-097e-4a38-badc-3900a939cd4b"),
                            Culture = "en",
                            MultiLangStringId = new Guid("a204fab0-4e36-49d0-8431-4f7bb8f8dd60"),
                            Value = "Lõvid on väga suured ja võimsa kehaehitusega. Isaste kehapikkus on 180–240 cm, saba pikkus 60–90 cm, mass 180–227 kg. Kere on sale, isegi kiitsakas. Pea on erakordselt massiivne, võrdlemisi pika koonuga. Jäsemed on lüheldased ja väga tugevad. Pikk saba lõpeb tutiga. Keha katab lühikene pruunikaskollane karvastik. Täiskasvanud isasloomal on pikk tumedam lakk, mis katab nii kaela, õlgu kui ka rinda."
                        },
                        new
                        {
                            Id = new Guid("af212ce5-8261-4366-8c1f-72818abb211f"),
                            Culture = "en",
                            MultiLangStringId = new Guid("a1bd7680-cc7a-4728-8138-177d2f8c075a"),
                            Value = "Japanese macaque"
                        },
                        new
                        {
                            Id = new Guid("103310d3-5c54-4479-b0c2-9f1f525e1a3d"),
                            Culture = "en",
                            MultiLangStringId = new Guid("9bffe23d-e223-40f3-acab-8e46733fc5b0"),
                            Value = "Jässaka kehaehituse ja tiheda karvakasukaga jaapani makaagid on kõige põhjapoolsema levikuga ahvid. Talvekülmade eest otsivad kaitset kuumaveeallikates. Tegutsevad nii puudel kui maapinnal, ujuvad ja sukelduvad suurepäraselt. Söövad puuvilju, taimede lehti ja juuri, putukaid, limuseid jms, ka pisiimetajaid. Elavad gruppidena, mida juhib tugev isasloom ja kus on selgelt välja kujunenud alluvussuhted. Omavahelisel suhtlemisel on tähtsal kohal häälitsused, miimika ja žestid. Pojad sünnivad enamasti kevad-suvel. Järglaste eest hoolitseb sageli ka isane. Loomaaias on elanud kuni 35 aastat vanaks."
                        },
                        new
                        {
                            Id = new Guid("9bd1023d-d5d2-42c1-8e89-f2d672ab3d77"),
                            Culture = "en",
                            MultiLangStringId = new Guid("a2233944-65a5-4dbd-a10e-76951285e28f"),
                            Value = "Chimpanzee"
                        },
                        new
                        {
                            Id = new Guid("a2f78bc2-b33d-41ee-8c55-412f26b5b855"),
                            Culture = "en",
                            MultiLangStringId = new Guid("70c61e1e-2081-4175-baa7-0e61293e8ed3"),
                            Value = "Asustavad metsi, võsastikke ja kohati ka lagedamaid alasid. Tegutsevad nii puudel kui maapinnal. Aktiivsed päeval, ööbivad puude otsa ehitatud pesades. Söövad puuvilju, lehti, seemneid, marju, putukaid. Vahel söövad šimpansid ka liha, püüdes üheskoos saagiks väiksemaid loomi. Elavad 20–30-isendilistes seltsingutes, kus valitseb keeruline võimujaotus. Karjasisestes suhetes on nad väga sallivad, kuid võõrast karjast sissetungijate vastu vaenulikud. Sigivad läbi aasta, pärast 230-päevast tiinust toob emane ilmale 1 poja. Emast võõrdumine algab u. 5. eluaastast. Suguküpsuse saavutavad 12–15-aastastena. Eluiga kuni 50 a. Geneetiliselt on šimpans inimese lähim elav sugulane. Šimpanseid ohustab vihmametsade hävitamine ja salaküttimine."
                        },
                        new
                        {
                            Id = new Guid("d72fda2b-a8e2-445a-a177-04b8f523befd"),
                            Culture = "en",
                            MultiLangStringId = new Guid("78d439fc-b991-418d-b7c9-9f06a64d32fc"),
                            Value = "Warhog"
                        },
                        new
                        {
                            Id = new Guid("8f7ed301-f264-46ba-b387-4e8e373e4434"),
                            Culture = "en",
                            MultiLangStringId = new Guid("2752af18-e1fb-4af8-a287-012bc9babc25"),
                            Value = "Asustavad savanne ja hõredaid põõsastikke, vältides tihedaid metsi. Elavad rühmades, kuhu kuulu-vad 1–3 emist koos põrsastega. Kuldid hoiavad eraldi. Tegutsevad päeval, veetes öö urus, kuhu täiskasvanud sisenevad tagurpidi, sulgedes uruava oma suure tüükalise peaga. Toituvad rohttaimedest, liikudes ringi poolroomates “põlvili”, esijäsemetel on randmeliigese kohal paksud mõhnad. Sigivad aasta läbi, kuigi enim poegi on vihmaperioodil. Jooksuajal teevad isased mootoripodinat meenutavat häält ja katsuvad rammu, surudes teineteist teelt, laubad vastamisi. Emane sünnitab urus 3–4 vöötideta põrsast."
                        },
                        new
                        {
                            Id = new Guid("17cea1fe-98e0-4609-a40a-c1f48c32ec9b"),
                            Culture = "en",
                            MultiLangStringId = new Guid("365173d7-2339-4722-8236-40845c621858"),
                            Value = "Gray seal pool"
                        },
                        new
                        {
                            Id = new Guid("55186b51-ffa4-404d-8a4c-82b6c9fa4850"),
                            Culture = "en",
                            MultiLangStringId = new Guid("17566ca3-1bfa-4388-a195-a8d2d8081682"),
                            Value = "Monkey cage - Japan macaque"
                        },
                        new
                        {
                            Id = new Guid("80a748f8-a5a5-44f1-96a2-c2a6dc5a07b4"),
                            Culture = "en",
                            MultiLangStringId = new Guid("1282b083-32af-4cc8-9577-96020c7049d1"),
                            Value = "Lion cage"
                        },
                        new
                        {
                            Id = new Guid("cd3112f8-4896-4d43-bd49-21fac33408fa"),
                            Culture = "en",
                            MultiLangStringId = new Guid("0b9ae366-0e78-47cc-a30d-aa2c7d4d57eb"),
                            Value = "Chimpanzee fence"
                        },
                        new
                        {
                            Id = new Guid("92d24e6c-5430-44f4-b30e-10d6ad8711c1"),
                            Culture = "en",
                            MultiLangStringId = new Guid("0056883d-1d16-4488-9b08-da57588c684c"),
                            Value = "Warhog pen"
                        });
                });

            modelBuilder.Entity("Domain._Shared.Statuses.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("Domain._Shared.Statuses.StatusInMapSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("ActiveDateTimeFrom");

                    b.Property<DateTime?>("ActiveDateTimeTo");

                    b.Property<bool>("IsActive");

                    b.Property<Guid>("MapSegmentId");

                    b.Property<Guid>("StatusId");

                    b.HasKey("Id");

                    b.HasIndex("MapSegmentId");

                    b.HasIndex("StatusId");

                    b.ToTable("StatusInMapSegment");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<Guid>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("fdc54f6e-c086-4649-b957-90c1d75b1416"),
                            RoleId = new Guid("2b913302-415f-4ec2-9c24-82a7bac22eef")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Domain.Animals.Animal", b =>
                {
                    b.HasOne("Domain.Animals.ConservationStatus", "ConservationStatus")
                        .WithMany("Animals")
                        .HasForeignKey("ConservationStatusId");

                    b.HasOne("Domain.MultiLangString", "Description")
                        .WithMany()
                        .HasForeignKey("DescriptionId");

                    b.HasOne("Domain.Media", "FeaturedImg")
                        .WithMany("Animals")
                        .HasForeignKey("FeaturedImgId");

                    b.HasOne("Domain.MultiLangString", "Name")
                        .WithMany()
                        .HasForeignKey("NameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Animals.ScientificClassification", "ScientificClassification")
                        .WithMany("Animals")
                        .HasForeignKey("ScientificClassificationId");
                });

            modelBuilder.Entity("Domain.Animals.AnimalFact", b =>
                {
                    b.HasOne("Domain.Animals.Animal", "Animal")
                        .WithMany("AnimalFacts")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.Animals.ConservationStatus", b =>
                {
                    b.HasOne("Domain.MultiLangString", "Name")
                        .WithMany()
                        .HasForeignKey("NameId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.Animals.MediaInAnimal", b =>
                {
                    b.HasOne("Domain.Animals.Animal", "Animal")
                        .WithMany("MediaInAnimals")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Media", "Media")
                        .WithMany("MediaInAnimals")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.Animals.SoundTrackInAnimal", b =>
                {
                    b.HasOne("Domain.Animals.Animal", "Animal")
                        .WithMany("AnimalSoundTracks")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.SoundTrack", "SoundTrack")
                        .WithMany("AnimalSoundtracks")
                        .HasForeignKey("SoundTrackId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.Map.GeoCoordinate", b =>
                {
                    b.HasOne("Domain.Map.MapSegment", "MapSegment")
                        .WithMany("GeoCoordinates")
                        .HasForeignKey("MapSegmentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.Map.MapSegment", b =>
                {
                    b.HasOne("Domain.Animals.Animal", "Animal")
                        .WithOne("MapSegment")
                        .HasForeignKey("Domain.Map.MapSegment", "AnimalId");

                    b.HasOne("Domain.Map.AppMap", "AppMap")
                        .WithMany("MapSegments")
                        .HasForeignKey("AppMapId");

                    b.HasOne("Domain.MultiLangString", "Name")
                        .WithMany()
                        .HasForeignKey("NameId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.Media", b =>
                {
                    b.HasOne("Domain.Identity.AppUser", "UploaderUser")
                        .WithMany("Medias")
                        .HasForeignKey("UploaderUserId");
                });

            modelBuilder.Entity("Domain.SoundTrack", b =>
                {
                    b.HasOne("Domain.Identity.AppUser", "UploaderUser")
                        .WithMany("SoundTracks")
                        .HasForeignKey("UploaderUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.Translation", b =>
                {
                    b.HasOne("Domain.MultiLangString", "MultiLangString")
                        .WithMany("Translations")
                        .HasForeignKey("MultiLangStringId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain._Shared.Statuses.StatusInMapSegment", b =>
                {
                    b.HasOne("Domain.Animals.Animal", "MapSegment")
                        .WithMany()
                        .HasForeignKey("MapSegmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain._Shared.Statuses.Status", "Status")
                        .WithMany("StatusInMapSegments")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Domain.Identity.AppRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Domain.Identity.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Domain.Identity.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Domain.Identity.AppRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Identity.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Domain.Identity.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
